ci: do not disable weak symbols on MacOS (Darwin)
Do not disable weak symbols on MacOS (Darwin),
because it causes the following error:

  LINK fio
ld: weak import of symbol '___darwin_check_fd_set_overflow' \
    not supported because of option: -no_weak_imports \
    for architecture x86_64
clang: error: linker command failed with exit code 1 \
    (use -v to see invocation)
make: *** [fio] Error 1
Error: Process completed with exit code 2.